### PR TITLE
Add Ultra-Rapid from russian source every 6 hours updated

### PR DESCRIPTION
**Pull request by gijskoning**
Constellations GPS, GLONASS, BEIDOU and GALILEO are included in these files.
The STARK_0 appears to be published first at in 01/29/2022

Verified new files coming in by running the script locally

### CODE REVIEW

**Comment by gregjhogan** [comment]
Why does HH range go from 00 to 39?

**Comment by pd0wm** [comment]
@gijskoning typo? guess it doesn't actually matter for the results

**Comment by gijskoning** [comment]
Yes thats a typo. It doesn't matter that much so will leave it

**Comment by gregjhogan** [comment]
@gijskoning please fix, otherwise anyone who reads it might wonder if it was a quirk about how they name the files or a typo (not sure what the down side of fixing it would be, seems like only upside)

**Comment by gijskoning** [comment]
You're right, will change it!

**Comment by gijskoning** [comment]
There was actually a bug too. Thanks for noticing :)
https://github.com/commaai/gnss-data-alt/pull/3

**Pull request merged**
